image: "ospr/g05:latest"

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - build

test:
    stage: test
    script:
        - make test
        
mem_test:
    stage: test
    script:
        - valgrind --error-exitcode=2 ./build/osmprun
