stages:
    - build
    - test
    
build:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - build

test:
    stage: test
    script:
        - make test
        