include:
  template: SAST.gitlab-ci.yml

stages:
    - build
    - test
    
build:
    stage: build
    script:
        - make
    artifacts:
        paths:
            - build

testsuite:
    stage: test
    script:
        - make test
        
mem_test:
    image: "git.fh-muenster.de:4567/ospr/g05:latest"
    stage: test
    script:
        - valgrind --error-exitcode=2 ./build/osmprun
