stages:
    - build
    - test
    
build:
    stage: build
    script:
        - echo "Building"
        - make

test:
    stage: test
    script:
        - echo "Testing"
        - make test
        