include:
  file: '/testsuite/.gitlab-ci.yml'
  template: SAST.gitlab-ci.yml

#stages:
#    - build
#    - test
#    
#build:
#    stage: build
#    script:
#        - make
#    artifacts:
#        paths:
#            - build
#
#testsuite:
#    stage: test
#    script:
#        - make test
#        
#mem_test:
#    image: "git.fh-muenster.de:4567/dk426722/libosmp:latest"
#    stage: test
#    script:
#        - valgrind --error-exitcode=2 ./build/osmprun
#